### ISSUE TITLE
db password and were to store files

### ISSUE THREAD

**Issue by janbulens** [lara-zeus/filament-installer#3]
Because you assume that the database user is root, without a password, if there is a password, the program will not run properly.
 The app is also placed in the installer folder.
Perhaps you can let users fill in this information themselves
- database admin
- database admin password
- where the app should be placed

**Comment by atmonshi** [comment]
sorry for the delay.

this package use the same code as the default laravel installer.
I think it can handle the third point, but for the others I will accept a PR :)
